{% set name = "PyGithub" %}
{% set version = "1.52" %}
{% set sha256 = "fc11a182ca3d88dde6ab2fbbd07e3441685cc8b738f7813fcbfc18be28c1d8ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python >=3
    - pyjwt
    - requests >=2.14.0
    - deprecated

test:
  requires:
    - pip
  imports:
    - github
  commands:
    - pip check

about:
  home: http://pygithub.github.io/PyGithub
  license_file: COPYING.LESSER
  license: LGPL-3.0-only
  license_family: LGPL
  summary: Python library implementing the GitHub API v3
