{% set name = "PyGithub" %}
{% set version = "1.55" %}
{% set sha256 = "1bbfff9372047ff3f21d5cd8e07720f3dbfdaf6462fcaed9d815f528f1ba7283" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python >=3
    - cryptography >=3.2
    - deprecated
    - pyjwt >=2
    - pynacl >=1.4
    - requests >=2.14.0,<2.25

test:
  requires:
    - pip
  imports:
    - github
  commands:
    - pip check

about:
  home: http://pygithub.github.io/PyGithub
  license_file: COPYING.LESSER
  license: LGPL-3.0-only
  license_family: LGPL
  summary: Python library implementing the GitHub API v3
